### ISSUE TITLE
Flat properties does not give expected result

### ISSUE THREAD

**Issue by planemad** [perliedman/query-overpass#5]
From the CLI ran `query-overpass query/blr-bus-stop.ql --flat-properties > output.geojson`

with this query
`[out:json][timeout:25];(node[highway=bus_stop](12.946554043930224,77.56158828735352,12.983816808126269,77.62420177459717););out body;>;out skel qt;`

This is the output: http://geojson.io/#id=gist:planemad/959c07b07f1d77aa100f&map=14/12.9659/77.5924

![screenshot 2016-01-22 17 55 05](https://cloud.githubusercontent.com/assets/126868/12510619/4b1332e0-c131-11e5-915b-1caddacecf36.png)

I was expecting `--flat-properties` to add the tags as `properties` and not nested under `tags`. Am I doing something wrong?

**Comment by planemad** [comment]
@perliedman @tryasd related to the latest commit 791f20d

**Comment by tyrasd** [comment]
Did you install query-overpass via npm? Because as far as I know, the latest (1.0.0) release doesn't yet include the flat-properties option (see https://github.com/perliedman/query-overpass/pull/4#issuecomment-172485932).

If you install it by using the latest code directly from github (`npm install -g perliedman/query-overpass`), it should work, though.

**Comment by planemad** [comment]
@tyrasd  thanks, that works!

**Comment by perliedman** [comment]
Just to let you know, I published version 1.1.0 just now, which contains this fix. Sorry about the delay.
